In [1]:
import numpy as np

#### Creating Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a=np.array([1,2,3,5,7,12])

In [7]:
a[2]

3

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  5,  7, 12])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

##### MultiDimensional Arrays

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
n[0,1] ### row number zero, column number 1

2

In [28]:
### if you wanna replace the values, use the assignment opertor
n[1,1]=20
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

#### Randomly Generated Arrays

In [34]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [38]:
#### to generate random integer numbers
np.random.seed(2)
np.random.randint(low=0,high=20,size=(5,2))

array([[ 8, 15],
       [13,  8],
       [11, 18],
       [11,  8],
       [ 7,  2]])

#### Element-Wise Operations

In [41]:
a =np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
a * 2

array([0, 2, 4, 6, 8])

In [44]:
b = (10 + (a * 2)) **2 /199

In [45]:
b

array([0.50251256, 0.72361809, 0.98492462, 1.28643216, 1.6281407 ])

In [46]:
a+b

array([0.50251256, 1.72361809, 2.98492462, 4.28643216, 5.6281407 ])

#### Comparison Operations

In [47]:
a >= b

array([False,  True,  True,  True,  True])

In [49]:
b

array([0.50251256, 0.72361809, 0.98492462, 1.28643216, 1.6281407 ])

In [48]:
a[a>b]

array([1, 2, 3, 4])

#### Summarizing Operations

In [50]:
a

array([0, 1, 2, 3, 4])

In [51]:
a.sum()

10

In [52]:
a.mean()

2.0

In [53]:
a.std()

1.4142135623730951